# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6457ebae0a70bb4088052f08e4c4662a7a6271bd8dba6a0eb77a3884b8307ad79c9e05dfc05c1c49a921313fde339a2728ca8dd1e0feb15d4eeb0e8b69396014

test:
  secret_key_base: 52265aa9134d6370011f2fd39eab6eaec49238490c0e0780b1f445aa0376758e5b1da35d2e08e1e81645f520a15f51e020dedef5b8429c3ebfe15f724f601ae6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
